### ISSUE TITLE
Proposal: Split dataset section into RGB / D  and add column if mesh annotation available

### ISSUE THREAD

**Issue by spurra** [xinghaochen/awesome-hand-pose-estimation#38]
Like the title suggests, I would like to propose to split the dataset section into RGB / D / RGB+D and add a column if the dataset comes with mesh annotations.

**Comment by xinghaochen** [comment]
Thanks very much for your great proposal. It's a good idea to split the datasets into RGB/D/RGB+D since there are quit a few hand pose datasets so far. I have just push a preliminary update  to refactor the dataset section.  However, more updates are still needed, e.g., complete missing columns and include more recently published datasets.  Pull requests are welcome :)
